name: ssh-setup
on: [push]
jobs: 
  connect:
    runs-on: ubuntu-latest
    steps:
      - uses: kielabokkie/ssh-key-and-known-hosts-action@v1.2.0
        with:
          # Private key required to access the host
          ssh-private-key: $SSH_KEY
          # Hostname or IP to add to the known hosts file
          ssh-host: $SSH_HOST
          # Port for key-scanning the server
          ssh-port: 22
