name: ssh-setup
on: 
  push:
    branches:
      - main
jobs: 
  connect:
    runs-on: ubuntu-latest
    steps:
      - uses: garygrossgarten/github-action-ssh@v0.6.3
        with:
          # Command to execute on the remote server.
          command: 'whoami'
          # Hostname or IP address of the server.
          host: ${{ secrets.SSH_HOST }}
          # Username for authentication.
          username: opc
          # Port number of the server.
          port: 22 # optional, default is 22
          # File Location or string that contains a private key for either key-based or hostbased user authentication (OpenSSH format)
          privateKey: ${{ secrets.SSH_KEY }}
