name: ssh-setup
on:
  push:
    branches:
      - ci-test
jobs:
  connect:
    runs-on: ubuntu-latest
    env:
      SSH_USER: "opc"
      SSH_KEY: ${{ secrets.SSH_KEY }}
      SSH_HOST: ${{ secrets.SSH_HOST }}
    steps:
      - name: Setup SSH access
        run: |
          mkdir -p ~/.ssh/
          echo "$SSH_KEY" > ~/.ssh/staging.key
          chmod 600 ~/.ssh/staging.key
          cat >>~/.ssh/config <<END
          Host staging
            HostName $SSH_HOST
            User $SSH_USER
            IdentityFile ~/.ssh/staging.key
            StrictHostKeyChecking no
          END
      - name: Pull the updates
        run: ssh staging '
          cd ~/reaction-backend &&
          git checkout main &&
          git pull &&
          npm install'
