name: ssh-setup
on:
  push:
    branches:
      - ci-test
jobs:
  connect:
    runs-on: ubuntu-latest
    env:
      SSH_USER: "root"
      SSH_KEY: ${{ secrets.SSH_KEY }}
      SSH_HOST: ${{ secrets.SSH_HOST }}
      DB_URI: ${{ secrets.DB_URI }}
      GMAIL_LOGIN: ${{ secrets.GMAIL_LOGIN }}
      GMAIL_PASSWORD: ${{ secrets.GMAIL_PASSWORD }}
    steps:
      - name: Setup SSH access
        run: |
          mkdir -p ~/.ssh/
          echo "$SSH_KEY" > ~/.ssh/staging.key
          chmod 600 ~/.ssh/staging.key
          cat >>~/.ssh/config <<END
          Host staging
            HostName $SSH_HOST
            User $SSH_USER
            IdentityFile ~/.ssh/staging.key
            StrictHostKeyChecking no
          END
      - name: Pull the updates
        run: ssh staging '
          export PATH=$PATH:/root/.nvm/versions/node/v14.16.1/bin &&
          export NODE_ENV=production &&
          export DB_URI="${{ secrets.DB_URI }}" &&
          export GMAIL_LOGIN=$GMAIL_LOGIN &&
          export GMAIL_PASSWORD=$GMAIL_PASSWORD &&
          export SERVER_URL="http://reaction-game.ru:1337" &&
          cd ~/reaction-backend &&
          git checkout ci-test &&
          git pull &&
          npm start'
