name: ssh-setup
on:
  push:
    branches:
      - ci-test
jobs:
  connect:
    runs-on: ubuntu-latest
    env:
      SSH_USER: "root"
      SSH_KEY: ${{ secrets.SSH_KEY }}
      SSH_HOST: ${{ secrets.SSH_HOST }}
      DB_HOST=: ${{ secrets.DB_HOST }}
      DB_NAME: ${{ secrets.DB_NAME }}
      DB_USER: ${{ secrets.DB_USER }}
      DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
      GMAIL_LOGIN: ${{ secrets.GMAIL_LOGIN }}
      GMAIL_PASSWORD: ${{ secrets.GMAIL_PASSWORD }}
    steps:
      - name: Setup SSH access
        run: |
          mkdir -p ~/.ssh/
          echo "$SSH_KEY" > ~/.ssh/staging.key
          chmod 600 ~/.ssh/staging.key
          cat >>~/.ssh/config <<END
          Host staging
            HostName $SSH_HOST
            User $SSH_USER
            IdentityFile ~/.ssh/staging.key
            StrictHostKeyChecking no
          END
      - name: Pull the updates
        run: ssh staging '
          source ~/.bashrc &&
          whoami &&
          nvm -v &&
          export NODE_ENV=production &&
          export DB_HOST=$DB_HOST &&
          export DB_NAME=$DB_NAME &&
          export DB_USER=$DB_USER &&
          export DB_PASSWORD=$DB_PASSWORD &&
          export GMAIL_LOGIN=$GMAIL_LOGIN &&
          export GMAIL_PASSWORD=$GMAIL_PASSWORD &&
          cd ~/reaction-backend &&
          git checkout main &&
          git pull &&
          node -v &&
          npm -v &&
          npm install &&
          npm run build &&
          npm start'
