name: ssh-setup
on:
  push:
    branches:
      - main
jobs:
  connect:
    runs-on: ubuntu-latest
    steps:
      - run: mkdir -p ~/.ssh
      - run: echo "${{ secrets.SSH_key }}" >> ~/.ssh/id_dsa
      - run: chmod 600 ~/.ssh/id_dsa
      - run: echo "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config
      - run: ssh ${{ secrets.SSH_HOST }} 'whoami'
