name: deploy
on:
  push:
    branches:
      - main
jobs:
  connect:
    runs-on: ubuntu-latest
    env:
      SSH_USER: "root"
      SSH_KEY: ${{ secrets.SSH_KEY }}
      SSH_HOST: ${{ secrets.SSH_HOST }}
      DB_URI: ${{ secrets.DB_URI }}
      GMAIL_LOGIN: ${{ secrets.GMAIL_LOGIN }}
      GMAIL_PASSWORD: ${{ secrets.GMAIL_PASSWORD }}
    steps:
      - name: Setup SSH access
        run: |
          mkdir -p ~/.ssh/
          echo "$SSH_KEY" > ~/.ssh/staging.key
          chmod 600 ~/.ssh/staging.key
          cat >>~/.ssh/config <<END
          Host staging
            HostName $SSH_HOST
            User $SSH_USER
            IdentityFile ~/.ssh/staging.key
            StrictHostKeyChecking no
          END
      - name: Pull the updates
        run: ssh staging '
          export PATH=$PATH:/root/.nvm/versions/node/v14.16.1/bin &&
          pm2 stop app &&
          export NODE_ENV=production &&
          export DB_URI="${{ secrets.DB_URI }}" &&
          export GMAIL_LOGIN=${{ secrets.GMAIL_LOGIN }} &&
          export GMAIL_PASSWORD=${{ secrets.GMAIL_PASSWORD }} &&
          export SERVER_URL="http://reaction-game.ru" &&
          cd ~/reaction-backend &&
          git checkout main &&
          git pull &&
          npm install &&
          npm run build &&
          pm2 start ecosystem.config.js'
